name: Collect CPI

on:
  schedule:
    - cron: "0 12 5,15,25 * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Deps
        run: |
          yarn install --production
      - name: Collect
        run: |
          yarn collect-cpi
      - name: Commit and Push
        run: |
          git config --global user.name 'alexk111'
          git config --global user.email 'alexk111@users.noreply.github.com'
          git add .
          git commit -am "Automated CPI collection"
          git push
