name: Collect Exchange Rates & Stocks

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Deps
        run: |
          yarn install --production
      - name: Collect Exch Rates
        run: |
          yarn collect-exchange-rates
        env:
          OXR_APP_ID: ${{ secrets.OXR_APP_ID }}
      - name: Collect Stocks
        run: |
          yarn collect-stocks
      - name: Commit and Push
        run: |
          git config --global user.name 'alexk111'
          git config --global user.email 'alexk111@users.noreply.github.com'
          git add .
          git commit -am "Automated data collection"
          git push
